name: Pull Request workflow
on:
  workflow_dispatch:
jobs:
  sample-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet build TestVsProject.sln -c Release
      - run: dotnet test TestVsProject.sln -c Release --no-restore

  
