name: Pull Request workflow
on:
  workflow_dispatch:
  pull_request:
    branches: 
      - '!main'
jobs:
  sample-job:
    runs-on: windows-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
      - name: .NET環境セットアップ
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: ビルド(NuGetパッケージ復元あり)
        run: dotnet build TestVsProject.sln -c Release
      - name: テスト(コンソール/TRX出力)
        run: dotnet test TestVsProject.sln -c Release --no-restore -l trx -l console
      - name: テストのレポート出力
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: テスト結果
          path: "./SampleUnitTest/TestResults/*.trx"
          reporter: dotnet-trx

  

